---
- name: Test Azure Collection
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Show installed collections
      command: ansible-galaxy collection list
      register: output
      changed_when: false

    - debug:
        var: output.stdout_lines
